### ISSUE TITLE
inconsistent error

### ISSUE THREAD

**Issue by bahcasac** [apexskier/go-template-validation#6]
![Screen Shot 2021-09-17 at 11 23 28](https://user-images.githubusercontent.com/22193883/133808319-f5db1abd-fef5-4a3d-b056-951183b00f6c.png)

This template works well for my use case, but the validator suggests to remove "\ and add ", such as:
`[
	{{range $key3, $param := .}}
	{{if eq $param.key "from"}}
		{\"key\": \"from\",\"value\" : \"0\"}
	{{else}}
		{\"key\": \"{{$param.key}}\",\"value\" : \"{{$param.value}}\"}
	{{end}}
	{{end}}
]`

**Comment by apexskier** [comment]
I suspect this is a legitimate error.

My initial question was: why are you escaping the quotes within the `if eq $params.key \"from\"`?

The tool is correctly calling out that that doesn't make sense. During parsing, it finds the keyword `if`, then looks for an expression that can be a boolean. It then finds `eq` and looks for two parameter expressions to compare. The first one is `$params.key`, which it understands is a variable reference and knows how to parse. The second one then starts with `\`, which it knows isn't allowed, since that won't be a variable or constant. You can see this error reproduced in [this playground](https://play.golang.org/p/UGzUAzDqcnK).

My guess is that you are trying to compare the param key against the literal string "from". I'm guessing you've copied this template directly from your source code and that it's wrapped in double quotes as an [interpreted string literal](https://golang.org/ref/spec#String_literals) in source. If that's the case, you're escaping all internal double quotes (`\"`) - which you shouldn't do with this tool, since it reads the template directly, unescaped.

If that guess is correct, I'd recommend replacing your template string with a [raw string literal](https://golang.org/ref/spec#String_literals) in source code - wrapped with `` ` `` characters. This is usually nicer to use for templates since you escape tildes instead of double quotes.

Your template would look like this, which validates correctly:

```
[
	{{range $key3, $param := .}}
	{{if eq $param.key "from"}}
	{"key": "from","value": "0"}
	{{end}}
	{{end}}
]
```

If this is what the issue is, I'll look into adding some warnings about this issue to the tool.

**Comment by apexskier** [comment]
I'm adding a feature in 9f6298d to support pasting the full string literal as a template (including wrapping quotes) and having the tool auto unescape it. It should make it much easier than manually unescaping everything.
